### PR TITLE
Changes to add support for dojox/mobile CodeGlass live examples

### PR DESCRIPTION
**Pull request by AdrianVasiliu**
Follow-up of e761077955264eedf73f1e1ca8b0299b759bea48
For the .py part of this older PR/commit, it appears that the .py code used for the static generation of HTML is different than the one used for the live generation (for instance on livedocs).
Hence, adapted the previous changes in src/dojo.py to dojocodeglass.py and dojowiki.py from export/source/_ext. 
Important: I tried to test these changes using the instructions at http://livedocs.dojotoolkit.org/developer/metadoc#creating-reference-guide-for-web-site, but on my Windows machine (under cygwin) it didn't work. Before going further it would need to be tested.

### CODE REVIEW

**Comment by kitsonk** [comment]
I should be able to take a look at it and merge it by this weekend at the latest.

Do you have a good example of the built docs I can look at to see if it fixes the issue?

**Comment by AdrianVasiliu** [comment]
Great, thanks Kitson.
You can test it by checking for instance this CodeGlass example: reference-guide/1.9/dojox/mobile/FilteredListMixin.html#declarative-example-filtered-roundrectlist
(you can compare with the similar example in http://livedocs.dojotoolkit.org/dojox/mobile/FilteredListMixin#declarative-example-filtered-roundrectlist , which works fine).

**Comment by kitsonk** [comment]
Ok, your example seems to be working on the built documentation now.  I will merge this PR.  I am going to be trying to move the reference-guide to git (because the SVN updates are very very challenging), so it might take a little bit to get it published to the live site.

**Comment by AdrianVasiliu** [comment]
Thanks a lot, Kitson.
Indeed, for now the live site doesn't seem updated yet, I'll check it from time to time.

**Pull request closed without merging**
