### PR TITLE
Changes to CodeGlass to add support for dojox/mobile live examples

### PR DESCRIPTION
**Pull request by AdrianVasiliu**
Changes to CodeGlass to add support for Dojo Mobile live examples: when the 'theme' param. of code-example is "deviceTheme", it imports dojox/mobile/deviceTheme.js using <script> instead of importing dijit's claro.css, and adds the hidden visibility style on <body> instead of setting the claro class.  Secondarily, improvements of the formatting/indentation of the generated source

### CODE REVIEW

**Comment by kitsonk** [comment]
Adrian, the git commit appears to be from "unknown".  It is you that is contributing the code?  Need to make sure it is clear from a CLA perspective.

**Comment by cjolif** [comment]
@kitsonk  Adrian is covered by IBM CCLA.

**Comment by AdrianVasiliu** [comment]
Yes, the commit is mine, sorry for the "unknown" - still learning git...

**Comment by AdrianVasiliu** [comment]
Just to add that the CodeGlass changes are consumed by live examples added to the dojo mobile refguide here:
https://github.com/dojo/docs/pull/65 (in dojox/mobile/FilteredListMixin.rst). Of course, I've also tested the non-regression for dijit code-examples.

**Comment by cjolif** [comment]
@AdrianVasiliu please read https://help.github.com/articles/set-up-git (in particular username section for the unknown issue I suppose)

**Comment by AdrianVasiliu** [comment]
yep, I've done that already... 1 min. after my commit ;-)

**Comment by kitsonk** [comment]
@cjolif I know he is covered by the IBM CCLA, it just didn't attribute his commit, so I wanted to make sure it was his work, not someone else.

**Comment by AdrianVasiliu** [comment]
Thanks kitsonk.

**Comment by AdrianVasiliu** [comment]
@kitsonk 
From what I can see, the rstwiki changes in my pull request have been merged, but are not yet deployed on http://livedocs.dojotoolkit.org/. Unless I'm wrong on that, would it be possible to deploy them?

**Pull request merged**
